# Document Project Workflow Configuration
name: "document-project"
version: "1.2.0"
description: 'Brownfield project documentation scanner. Use when the user says "lets create project documentation" or "I want to document a brownfield project"'
author: "BMad"

# Critical variables
config_source: "{project-root}/_bmad/gds/config.yaml"
output_folder: "{config_source}:project_knowledge"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
game_dev_experience: "{config_source}:game_dev_experience"
date: system-generated

# Module path and component files
installed_path: "{project-root}/_bmad/gds/workflows/document-project"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Required data files - CRITICAL for project type detection and documentation requirements
documentation_requirements_csv: "{installed_path}/documentation-requirements.csv"

# Output configuration - Multiple files generated in output folder
# Primary output: {output_folder}/project-documentation/
# Additional files generated by sub-workflows based on project structure

standalone: true
