name: dev-story
description: 'Story implementation and testing workflow. Use when the user says "lets implement story tasks" or "lets write tests for story"'
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/gds/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
game_dev_experience: "{config_source}:game_dev_experience"
document_output_language: "{config_source}:document_output_language"
story_dir: "{config_source}:implementation_artifacts"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/gds/workflows/4-production/dev-story"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

story_file: "" # Explicit story path; auto-discovered if empty
implementation_artifacts: "{config_source}:implementation_artifacts"
sprint_status: "{implementation_artifacts}/sprint-status.yaml"
project_context: "**/project-context.md"

standalone: true
