# Sprint Status - Game Development Implementation Tracker
name: sprint-status
description: 'Sprint status summary and risk surfacing. Use when the user says "Summarize sprint-status.yaml for game project and surface risks"'
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/gds/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated
implementation_artifacts: "{config_source}:implementation_artifacts"
planning_artifacts: "{config_source}:planning_artifacts"
project_context: "**/project-context.md"

# Workflow components
installed_path: "{project-root}/_bmad/gds/workflows/4-production/sprint-status"
instructions: "{installed_path}/instructions.md"

# Inputs
variables:
  sprint_status_file: "{implementation_artifacts}/sprint-status.yaml"
  tracking_system: "file-system"

# Smart input file references
input_file_patterns:
  sprint_status:
    description: "Sprint status file generated by sprint-planning"
    whole: "{implementation_artifacts}/sprint-status.yaml"
    load_strategy: "FULL_LOAD"

# Standalone so IDE commands get generated
standalone: true

# No web bundle needed