bmad:
  model:
    path: "E:/Model/Qwen_Qwen3-0.6B-Q4_K_M.gguf"
    off-heap: true
  search:
    min-score: 0.6

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
